In [1]:
import numpy as np

In [3]:
my_array=np.array([3,6,32,7])

In [4]:
my_array

array([ 3,  6, 32,  7])

In [5]:
my_array.dtype

dtype('int32')

In [6]:
my_array=np.array([3,6,32,7],np.int8)

In [7]:
my_array

array([ 3,  6, 32,  7], dtype=int8)

In [8]:
my_array.dtype

dtype('int8')

In [9]:
my_array[0,1]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [19]:
my_array=np.array([[3,6,32,7]])

In [11]:
my_array[0,1]

6

In [12]:
my_array.shape

(1, 4)

In [14]:
my_array.size

4

In [15]:
my_array.dtype

dtype('int32')

In [22]:
my_array[0,1]=45

In [23]:
my_array

array([[ 3, 45, 32,  7]])

# methods

In [24]:
# array creation conversion from other python structure

In [26]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [27]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr1.dtype

dtype('int32')

In [29]:
arr1.shape

(3, 3)

In [30]:
arr1.size

9

In [32]:
arr1[0]

array([1, 2, 3])

In [33]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [34]:
zeros=np.zeros((2,5))

In [35]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [42]:
zeros=np.zeros((2,5)*1)

In [41]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [43]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [68]:
k=np.linspace(1,50,6)
k

array([ 1. , 10.8, 20.6, 30.4, 40.2, 50. ])

In [66]:
emp=np.empty((4,6))

In [67]:
emp

array([[1.01512663e-311, 7.60861095e-322, 0.00000000e+000,
        0.00000000e+000, 1.89146896e-307, 1.15998412e-028],
       [4.31603868e-080, 1.94919985e-153, 1.35717430e+131,
        1.04884745e-153, 1.05191681e-153, 1.04885944e-153],
       [1.05191966e-153, 1.04884749e-153, 1.05191682e-153,
        1.04885945e-153, 1.02512875e+136, 6.01347002e-154],
       [1.93773699e-109, 4.90900643e+252, 1.94918511e-153,
        6.32672800e+180, 4.74483502e+170, 5.55151217e-048]])

In [69]:
emp2=np.empty_like((k))

In [70]:
emp2

array([ 1. , 10.8, 20.6, 30.4, 40.2, 50. ])

In [71]:
p=np.arange(88)

In [72]:
p

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87])

In [73]:
p.shape

(88,)

In [74]:
p.size

88

In [75]:
p.dtype

dtype('int32')

In [76]:
p.ndim

1

In [87]:
p.reshape(4,22)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
        38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
        60, 61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87]])

In [88]:
p.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87])

In [89]:
# 

In [95]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [96]:
arr=np.array(x)

In [97]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [98]:
arr.sum(axis=0)

array([12,  8,  9])

In [99]:
arr.sum(axis=1)

array([ 6, 15,  8])

In [100]:
arr.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [102]:
for items in arr:
    print(items)

[1 2 3]
[4 5 6]
[7 1 0]


In [103]:
arr.flat

In [104]:
for items in arr.flat:
    print(items)

1
2
3
4
5
6
7
1
0


In [105]:
arr.ndim

2

In [106]:
arr.size

9

In [107]:
arr.shape

(3, 3)

In [108]:
arr.nbytes

36

In [109]:
one=np.array([1,3,4,634,2])

In [110]:
one.argmax()

3

In [111]:
one.argmin()

0

In [112]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [114]:
one.argpartition

<function ndarray.argpartition>

In [115]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [116]:
arr.argmax()

6

In [117]:
arr.argmin()

8

In [118]:
arr.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [119]:
arr.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [120]:
arr.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [121]:
arr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [124]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [122]:
arr2 =([[1,2,1],
       [4,0,6],
       [8,1,0]])

In [125]:
arr1*arr2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  8,  0]])

In [126]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [128]:
arr1.sum()

45

In [129]:
arr1.max()

9

In [132]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [133]:
np.where(arr1>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [130]:
np.where(arr1>4)

(array([1, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))